apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ instance_name }}-daoshop-product
  labels:
    app: {{ instance_name }}-daoshop-product
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-daoshop-product
  template:
    metadata:
      labels:
        app: {{ instance_name }}-daoshop-product
    spec:
      imagePullSecrets:
      - name: harbor
      initContainers:
        - name: dx-monitor-agent-sidecar
          image: registry.dx.io/daocloud-dmp/dx-monitor-agent-sidecar:latest
          imagePullPolicy: IfNotPresent
          command: ["cp", "-r", "/sidecar", "/target"]
          volumeMounts:
            - name: sidecar
              mountPath: /target
      containers:
      - image: {{ daoshop-product.image }}
        name: {{ instance_name }}-daoshop-product
        resources:
          requests:
            memory: "2000Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
          readOnly: true
        env:
            - name: JAVA_OPTS
              value: "-javaagent:/sidecar/sidecar/skywalking/agent/skywalking-agent.jar -javaagent:/sidecar/sidecar/vedfolnir/vedfolnir-agent.jar"
            - name: DAOCLOUD_DC_SERVER
              value: "http://dx.hypo.vip/api/sail/v2/cluster/environments"
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/service-name'']'
            - name: AGENT_INSTANCE_UUID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'     
            - name: AGENT_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'
            - name: DMP_ENVIRONMENT_CODE
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/env-id'']'
            - name: DX_APPLICATION_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-name'']'
            - name: DX_APPLICATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-id'']'
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: dx-skywalking-oap-ng.dx-pilot.svc:11800
            - name: VEDFOLNIR_SERVER_URL
              value: ws://dmp-vedfolnir-manager.dx-pilot.svc:8002
      volumes:
        - name: sidecar  #共享agent文件夹
          emptyDir: {}
        - name: host-time
          hostPath:
            path: /etc/localtim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ instance_name }}-daoshop-order
  labels:
    app: {{ instance_name }}-daoshop-order
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-daoshop-order
  template:
    metadata:
      labels:
        app: {{ instance_name }}-daoshop-order
    spec:
      initContainers:
        - name: dx-monitor-agent-sidecar
          image: registry.dx.io/daocloud-dmp/dx-monitor-agent-sidecar:latest
          imagePullPolicy: IfNotPresent
          command: ["cp", "-r", "/sidecar", "/target"]
          volumeMounts:
            - name: sidecar
              mountPath: /target
      imagePullSecrets:
      - name: harbor
      containers:
      - image: {{ daoshop-order.image }}
        name: {{ instance_name }}-daoshop-order
        resources:
          requests:
            memory: "2000Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
          readOnly: true
        env:
            - name: JAVA_OPTS
              value: "-javaagent:/sidecar/sidecar/skywalking/agent/skywalking-agent.jar -javaagent:/sidecar/sidecar/vedfolnir/vedfolnir-agent.jar"
            - name: DAOCLOUD_DC_SERVER
              value: "http://dx.hypo.vip/api/sail/v2/cluster/environments"
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/service-name'']'
            - name: AGENT_INSTANCE_UUID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'     
            - name: AGENT_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'
            - name: DMP_ENVIRONMENT_CODE
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/env-id'']'
            - name: DX_APPLICATION_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-name'']'
            - name: DX_APPLICATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-id'']'
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: dx-skywalking-oap-ng.dx-pilot.svc:11800
            - name: VEDFOLNIR_SERVER_URL
              value: ws://dmp-vedfolnir-manager.dx-pilot.svc:8002
      volumes:
        - name: sidecar  #共享agent文件夹
          emptyDir: {}
        - name: host-time
          hostPath:
            path: /etc/localtim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ instance_name }}-daoshop-user-center
  labels:
    app: {{ instance_name }}-daoshop-user-center
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-daoshop-user-center
  template:
    metadata:
      labels:
        app: {{ instance_name }}-daoshop-user-center
    spec:
      initContainers:
        - name: dx-monitor-agent-sidecar
          image: registry.dx.io/daocloud-dmp/dx-monitor-agent-sidecar:latest
          imagePullPolicy: IfNotPresent
          command: ["cp", "-r", "/sidecar", "/target"]
          volumeMounts:
            - name: sidecar
              mountPath: /target
      imagePullSecrets:
      - name: harbor
      containers:
      - image: {{ daoshop-user-center.image }}
        name: {{ instance_name }}-daoshop-user-center
        resources:
          requests:
            memory: "2000Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
          readOnly: true
        env:
            - name: JAVA_OPTS
              value: "-javaagent:/sidecar/sidecar/skywalking/agent/skywalking-agent.jar -javaagent:/sidecar/sidecar/vedfolnir/vedfolnir-agent.jar"
            - name: DAOCLOUD_DC_SERVER
              value: "http://dx.hypo.vip/api/sail/v2/cluster/environments"
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/service-name'']'
            - name: AGENT_INSTANCE_UUID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'     
            - name: AGENT_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'
            - name: DMP_ENVIRONMENT_CODE
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/env-id'']'
            - name: DX_APPLICATION_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-name'']'
            - name: DX_APPLICATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-id'']'
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: dx-skywalking-oap-ng.dx-pilot.svc:11800
            - name: VEDFOLNIR_SERVER_URL
              value: ws://dmp-vedfolnir-manager.dx-pilot.svc:8002
      volumes:
        - name: sidecar  #共享agent文件夹
          emptyDir: {}
        - name: host-time
          hostPath:
            path: /etc/localtim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ instance_name }}-daoshop-shop-admin
  labels:
    app: {{ instance_name }}-daoshop-shop-admin
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-daoshop-shop-admin
  template:
    metadata:
      labels:
        app: {{ instance_name }}-daoshop-shop-admin
    spec:
      initContainers:
        - name: dx-monitor-agent-sidecar
          image: registry.dx.io/daocloud-dmp/dx-monitor-agent-sidecar:latest
          imagePullPolicy: IfNotPresent
          command: ["cp", "-r", "/sidecar", "/target"]
          volumeMounts:
            - name: sidecar
              mountPath: /target
      imagePullSecrets:
      - name: harbor
      containers:
      - image: {{ daoshop-admin.image }}
        name: {{ instance_name }}-daoshop-shop-admin
        resources:
          requests:
            memory: "2000Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
          readOnly: true
        env:
            - name: JAVA_OPTS
              value: "-javaagent:/sidecar/sidecar/skywalking/agent/skywalking-agent.jar -javaagent:/sidecar/sidecar/vedfolnir/vedfolnir-agent.jar"
            - name: DAOCLOUD_DC_SERVER
              value: "http://dx.hypo.vip/api/sail/v2/cluster/environments"
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/service-name'']'
            - name: AGENT_INSTANCE_UUID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'     
            - name: AGENT_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'
            - name: DMP_ENVIRONMENT_CODE
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/env-id'']'
            - name: DX_APPLICATION_NAME
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-name'']'
            - name: DX_APPLICATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''dx.daocloud.io/application-id'']'
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: dx-skywalking-oap-ng.dx-pilot.svc:11800
            - name: VEDFOLNIR_SERVER_URL
              value: ws://dmp-vedfolnir-manager.dx-pilot.svc:8002
          volumeMounts:
            - name: sidecar
              mountPath: /sidecar
      volumes:
        - name: sidecar  #共享agent文件夹
          emptyDir: {}
        - name: host-time
          hostPath:
            path: /etc/localtim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ instance_name }}-daoshop-ui
  labels:
    app: {{ instance_name }}-daoshop-ui
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-daoshop-ui
  template:
    metadata:
      labels:
        app: {{ instance_name }}-daoshop-ui
    spec:
      imagePullSecrets:
      - name: harbor
      containers:
      - image: {{ daoshop-ui.image }}
        name: {{ instance_name }}-daoshop-ui
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
          readOnly: true
        env:
        - name: BASE_URL
          value: "{{ gateway_runtime_url }}"
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ instance_name }}-daoshop-ui
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ daoshop_ui_port }}
  selector:
    app: {{ instance_name }}-daoshop-ui

